### ISSUE TITLE
Prettifying index.html

### ISSUE THREAD

**Issue by R4356th** [Glitchy-Scratch/glitchy-scratch.github.io#15]
#13 prettified all JS and CSS files but index.html was left out. Prettifying this is not very important but the prettified version is easy-to-read. Back when I was updating the news and other stuff in that file, it was very hard to edit it. The prettified code can be seen [here](https://glitch.com/edit/#!/glitchy-scratch?path=index.html%3A5019%3A52). // cc @Glitchy-Scratch/contributors

**Comment by GrahamSH-LLK** [comment]
Let's use prettier.
