### ISSUE TITLE
Scratch URL is actually the link to our homepage

### ISSUE THREAD

**Issue by R4356th** [Glitchy-Scratch/glitchy-scratch.github.io#18]
The link to Scratch in the What's Happening section is actually the link to our homepage.

**Comment by GrahamSH-LLK** [comment]
I'll fix that.

**Comment by R4356th** [comment]
This issue has been fixed, thanks to @GrahamSH-LLK in 7084d34db23ba9d6c222d694b5218afbb43dc4db
