### ISSUE TITLE
@R4356th seems to be logged in

### ISSUE THREAD

**Issue by GrahamSH-LLK** [Glitchy-Scratch/glitchy-scratch.github.io#8]
When you first access the site, @R4356th R4356th shows up in the username spot and projects flash, before it becomes blank. Is this intended?

**Comment by R4356th** [comment]
No, @GrahamSH-LLK, this is not intended.

**Comment by Thingyman-DEV** [comment]
I am a good friend of GrahamSH. I may be able to help but do not have much javascript experience. Is this a html problem?

**Comment by GrahamSH-LLK** [comment]
@Thingyman-DEV Not sure. I think the Glitchy_Scratch_Files folder is part of the problem. We might have to replace those files with blank images of the same size.

**Comment by Thingyman-DEV** [comment]
@GrahamSH-LLK Ok, I’ll look into it

**Comment by Thingyman-DEV** [comment]
@GrahamSH-LLK @R4356th I have found the file. It is 45719749_32x32.png
 in Glitchy_scratch_files

**Comment by Thingyman-DEV** [comment]
@R4356th @GrahamSH-LLK Both the username and profile picture can be found in line 3341 of index.html. I will try to create a fork to see if removing part of that line will work

**Comment by R4356th** [comment]
@Thingyman-DEV, thank you! I know where the bug is and how to fix that issue. You can go ahead and make a pull request to fix this issue.

**Comment by Thingyman-DEV** [comment]
@R4356th Ok, I made the request. If I did something wrong tell me because I'm new to github

**Comment by GrahamSH-LLK** [comment]
It looks good!

**Comment by R4356th** [comment]
Resolved by #9.
